MODEL_NAME ="google/flan-t5-small"
MODEL_OUTPUT_DIR = "models/text-simplifier/OneStop"

MAX_INPUT_LENGTH = 256
MAX_TARGET_LENGTH = 256

BATCH_SIZE = 16
EPOCHS = 5
LEARNING_RATE = 3e-5

NUM_BEAMS = 4
LENGTH_PENALTY = 0.8
MIN_LENGTH_RATIO = 0.2
SIMILARITY_THRESHOLD = 0.9
SEED = 42